name: bioc0016-machinelearning
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - matplotlib>=3.1.1
  - numpy>=1.17.3
  - scipy>=1.3.1
  - scikit-image
  - torch
  - torchvision
  - pip:
    - ipyannotation
